### ISSUE TITLE
Remove Thumbnail

### ISSUE THREAD

**Issue by index-js** [seatonjiang/kratos#383]
[Can remove thumbnail here Next？](https://github.com/vtrois/kratos/blob/main/inc/theme-article.php#L105)
[Like this](https://github.com/vtrois/kratos/blob/main/inc/theme-setting.php#L111)

I used CDN URL, no thumb pic.
Thanks！
So I can follow your refresh.

**Comment by index-js** [comment]
Or add a switch in the admin

**Comment by index-js** [comment]
g_removeimgsize is used
https://github.com/vtrois/kratos/blob/main/inc/theme-core.php#L199

**Comment by n0099** [comment]
u can add following code to custom/custom.php:
```php
add_action('init', function () {
    remove_image_size('kratos-thumbnail');
});
```

**Comment by index-js** [comment]
Not Work
https://github.com/vtrois/kratos/blob/main/inc/theme-article.php#L112

**Comment by index-js** [comment]
> u can add following code to custom/custom.php:
> 
> ```
> add_action('init', function () {
>     remove_image_size('kratos-thumbnail');
> });
> ```

**Comment by n0099** [comment]
> u can add following code to custom/custom.php:
> 
> ```
> add_action('init', function () {
>     remove_image_size('kratos-thumbnail');
> });
> ```

try removing add_action() wrapper, since init hooks is fired before custom.php is required at https://github.com/vtrois/kratos/blob/27ed0d05b8d4afa06d0b85dd264fef5344b16419/functions.php#L45

**Comment by index-js** [comment]
Nonono
function post_thumbnail() is used

This line will report an error
https://github.com/vtrois/kratos/blob/main/inc/theme-article.php#L112

**Comment by n0099** [comment]
In my environment if post thumbnail(aka featured image) had not been set, `get_post_thumbnail_id()` will return `NULL`, then `wp_get_attachment_image_src()` will return `FALSE`, since there's no post thumbnail, the only usage of `$img_url` in the `if (has_post_thumbnail() == true)` branch will be skipped, resulting neither exception nor error will be occurred.
If post thumbnail had been set, `wp_get_attachment_image_src($img_id, 'kratos-thumbnail')` will return
```php
array(4) {
 [0]=>
 string(71) "http://url/to/image"
 [1]=>
 int(250)
 [2]=>
 int(250)
 [3]=>
 bool(false)
}
```
so it's ok to be used.

**Comment by index-js** [comment]
Fine, Thanks.
