### ISSUE TITLE
似乎新版本的图片上传之后没法显示？

### ISSUE THREAD

**Issue by depthsky2016** [seatonjiang/kratos#68]
**问题描述**

在新版本的主题下上传图片之后没法加载出媒体列表，不知道是什么原因，对应查看了网上的一些[解决方案](http://www.heyby.cn/p_meitiku.html)，但是依旧没有发现问题所在，不知道是不是主题的原因，谢谢。

Update：换了主题之后显示没有问题，重装本主题之后问题复现，所以有可能是主题的问题，不知道在您这里这个问题会不会复现，谢谢。

**产生环境**

- 设备：Mac OS Mojave  10.14
- 浏览器及版本：各浏览器均测试过
- 演示地址：

**复现步奏**

1. 文件上传状态

<img width="1112" alt="2018-11-22 2 08 25" src="https://user-images.githubusercontent.com/19619104/48884639-4794b800-ee60-11e8-98c4-7d5a8b30f8ff.png">

2. 文件已经存在

<img width="825" alt="2018-11-22 2 09 13" src="https://user-images.githubusercontent.com/19619104/48884648-54b1a700-ee60-11e8-83d9-2245ac767cc0.png">

3. 图片插入页

<img width="890" alt="2018-11-22 2 08 58" src="https://user-images.githubusercontent.com/19619104/48884657-61ce9600-ee60-11e8-9384-4575190b094b.png">

4：媒体库页

<img width="890" alt="2018-11-22 2 08 58" src="https://user-images.githubusercontent.com/19619104/48884678-727f0c00-ee60-11e8-9227-f44930693b60.png">

**Comment by ghost** [comment]
换到默认主题看一下正常吗？ 在2018年11月22日 14:11，depthsky2016 写道： 问题描述 在新版本的主题下上传图片之后没法加载出媒体列表，不知道是什么原因，对应查看了网上的一些解决方案，但是依旧没有发现问题所在，不知道是不是主题的原因，谢谢。 产生环境 设备：Mac OS Mojave 10.14 浏览器及版本：各浏览器均测试过 演示地址： 复现步奏 文件上传状态 文件已经存在 图片插入页 4：媒体库页 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by yuki-node** [comment]
请问这个问题解决了么，最新的主题依然不能显示图片

**Comment by ghost** [comment]
这里测试正常，建议你 F12 抓包看一下
