### ISSUE TITLE
第一次访问会有两个滚动条

### ISSUE THREAD

**Issue by rogosome** [seatonjiang/kratos#71]
**问题描述**

第一次访问网页会有两个滚动条，刷新后正常，清除缓存再载入后还是两个滚动条，貌似刷新一次就会消失- -，如下
https://www.rogoso.info/wp-content/uploads/2018/11/scrollbar.PNG

**产生环境**

- 设备：PC
- 浏览器及版本：Chrome 70.0.3538.110 （64 位）
- 演示地址：https://www.rogoso.info/

**复现步奏**

1. 第一次访问会有两个滚动条
2. 刷新后消失，ctrl+F5后出现- -

**Comment by ghost** [comment]
周末看下 在2018年11月28日 20:10，rogosome 写道： 问题描述 第一次访问网页会有两个滚动条，刷新后正常，清除缓存再载入后还是两个滚动条，貌似刷新一次就会消失- -，如下图 https://www.rogoso.info/wp-content/uploads/2018/11/scrollbar.png 产生环境 设备：PC 浏览器及版本：Chrome 70.0.3538.110 （64 位） 演示地址：https://www.rogoso.info/ 复现步奏 第一次访问会有两个滚动条 刷新后消失，ctrl+F5后出现- - — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by seatonjiang** [comment]
这个问题已经在 3.0.0 版本中修复，还请升级测试
